#!/usr/bin/env bash
# (sudo chmod u+x pre-commit && cd .git/hooks && ln -s ../../pre-commit .)
# https://stagerightlabs.com/blog/automatic-code-formatting-with-git-hooks
set -e
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.py')
if \[ -n "$CHANGED_FILES" \]; then
    black $CHANGED_FILES;
    git add $CHANGED_FILES;
fi
